package util

actual fun handleError(throwable: Throwable) {
    throw throwable
}
